<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.6*" />
    <PackageReference Include="TUnit.Mocks" Version="1.65.68" />
    <PackageReference Include="TUnit.Mocks.Logging" Version="1.65.68" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlatCopy.FileSystemServices\FlatCopy.FileSystemServices.csproj" />
  </ItemGroup>

</Project>
